window.SITE_CONTENT = {
  privacy: {
    meta: "",
    title: "Privacy Policy",
    intro:
      "<p>This site is intentionally minimal. It does not use analytics, advertising trackers, user accounts, or marketing forms. The goal is to keep the site straightforward while still being transparent about the few external services and browser-side preferences that are involved.</p>",
    details:
      "<h2>What this site collects</h2><p>This site does not directly collect personal information through signup forms, comment systems, analytics dashboards, or advertising tools.</p><p>Like most websites, basic request information may still be handled by your browser, your internet provider, and the hosting infrastructure used to deliver the page.</p><h2>Google Fonts</h2><p>This site loads Google Fonts for typography. When a page loads, your browser may request font files from Google servers. That can expose technical request information such as your IP address, browser details, and standard web request metadata to Google.</p><h2>Local browser storage</h2><p>This site stores a small browser-side preference for text casing so your selected text display mode can persist between visits on the same device. This preference is stored locally in your browser and is not used for advertising, tracking across sites, or account profiling.</p><h2>Image use and copying</h2><p>Photographs and visual work on this site are personal work by Alan Dautov unless otherwise noted. Please do not copy, download, repost, reuse, redistribute, sell, or use these images in public projects without written permission. Normal browser caching that happens while viewing the site is expected and does not grant reuse rights.</p><h2>External links and platforms</h2><p>This site includes links to external services such as LinkedIn, GitHub, Telegram, Google Maps, and email or phone actions. If you choose to open those links or contact through those platforms, the destination service may collect its own data under its own privacy policy and terms.</p><h2>Direct communication</h2><p>If you contact Alan Dautov by email, phone, or a linked third-party platform, that communication is handled by the relevant provider rather than by a custom backend on this site.</p><h2>Changes</h2><p>This privacy policy may be updated if the site adds new services, embeds, analytics, forms, or other data-handling features in the future.</p>",
  },
};
